# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sten/Desktop/Digital-Systems-Development/Labo 4-5/micro_pwm/micro_pwm.srcs/sources_1/bd/micro_pwm/ip/micro_pwm_lmb_bram_0/micro_pwm_lmb_bram_0.xci
# IP: The module: 'micro_pwm_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sten/Desktop/Digital-Systems-Development/Labo 4-5/micro_pwm/micro_pwm.gen/sources_1/bd/micro_pwm/ip/micro_pwm_lmb_bram_0/micro_pwm_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_pwm_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sten/Desktop/Digital-Systems-Development/Labo 4-5/micro_pwm/micro_pwm.srcs/sources_1/bd/micro_pwm/ip/micro_pwm_lmb_bram_0/micro_pwm_lmb_bram_0.xci
# IP: The module: 'micro_pwm_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sten/Desktop/Digital-Systems-Development/Labo 4-5/micro_pwm/micro_pwm.gen/sources_1/bd/micro_pwm/ip/micro_pwm_lmb_bram_0/micro_pwm_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_pwm_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
