# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.srcs/sources_1/ip/MMCM/MMCM.xci
# IP: The module: 'MMCM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.gen/sources_1/ip/MMCM/MMCM_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.gen/sources_1/ip/MMCM/MMCM.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.gen/sources_1/ip/MMCM/MMCM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.srcs/sources_1/ip/MMCM/MMCM.xci
# IP: The module: 'MMCM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.gen/sources_1/ip/MMCM/MMCM_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.gen/sources_1/ip/MMCM/MMCM.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/____School/AP/2023-2024/Digital-Systems-Development/Labo 1-3/Sten_Hulsbergen_DSP_FPGA/Sten_Hulsbergen_DSP_FPGA.gen/sources_1/ip/MMCM/MMCM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
